# Generated by Django 4.2.16 on 2025-03-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0002_remove_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='payement_status',
            field=models.CharField(choices=[('actif', 'Actif'), ('suspended', 'Suspended')], default='actif', max_length=100),
        ),
    ]
