# Generated by Django 4.2.16 on 2024-10-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('air_temperature', models.FloatField()),
                ('wetbulb_temperature', models.FloatField()),
                ('solar_radiation', models.FloatField()),
                ('vpd', models.FloatField()),
                ('relative_humidity', models.FloatField()),
                ('precipitation', models.FloatField()),
                ('leaf_wetness', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('solar_panel_voltage', models.FloatField()),
                ('battery_voltage', models.FloatField()),
                ('delta_t', models.FloatField()),
                ('sunshine_duration', models.FloatField()),
                ('et0', models.FloatField()),
            ],
        ),
    ]
