# Generated by Django 5.1.1 on 2024-10-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_dashboardsensordata'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('et0', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('wind_direction', models.FloatField()),
                ('cumulative_rainfall', models.FloatField()),
                ('solar_radiation', models.FloatField()),
                ('vapor_pressure_deficit', models.FloatField()),
                ('precipitation', models.FloatField()),
            ],
        ),
    ]
