# Generated by Django 5.1.1 on 2024-11-07 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_dashboardsensordata_user_stationdata_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A brief title for the alert.', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the alert.')),
                ('danger_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', help_text='Indicates the severity of the alert (Low, Medium, High).', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yesterday_temperature', models.DecimalField(decimal_places=2, help_text='Temperature recorded yesterday in Celsius.', max_digits=5)),
                ('today_temperature', models.DecimalField(decimal_places=2, help_text='Temperature recorded today in Celsius.', max_digits=5)),
                ('yesterday_humidity', models.DecimalField(decimal_places=2, help_text='Humidity recorded yesterday as a percentage.', max_digits=5)),
                ('today_humidity', models.DecimalField(decimal_places=2, help_text='Humidity recorded today as a percentage.', max_digits=5)),
                ('ET0', models.DecimalField(decimal_places=2, help_text='Reference evapotranspiration in mm/day.', max_digits=6)),
                ('soil_humidity', models.DecimalField(decimal_places=2, help_text='Soil humidity percentage.', max_digits=5)),
                ('soil_temperature', models.DecimalField(decimal_places=2, help_text='Soil temperature in Celsius.', max_digits=5)),
                ('soil_ph', models.DecimalField(decimal_places=2, help_text='Soil pH level.', max_digits=4)),
                ('perfect_irrigation_period', models.CharField(help_text='Ideal time period for irrigation.', max_length=100)),
                ('last_irrigation_date', models.DateField(help_text='Date of the last irrigation.')),
                ('last_start_irrigation_hour', models.TimeField(help_text='Start time of the last irrigation.')),
                ('last_finish_irrigation_hour', models.TimeField(help_text='Finish time of the last irrigation.')),
                ('used_water_irrigation', models.DecimalField(decimal_places=2, help_text='Water used in the last irrigation in liters.', max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='AlertsPerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the user has read this alert')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.alert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationsPerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the user has read this notification')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
