# Generated by Django 5.1.1 on 2024-11-08 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_alert_notification_alertsperuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_date',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Date and time when the notification was created.'),
        ),
    ]
