# Generated by Django 4.2.16 on 2025-01-21 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0006_notification_notification_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the sensor data was recorded.')),
                ('precipitation_rate', models.FloatField(help_text='Precipitation rate in mm/h.')),
                ('humidity_weather', models.FloatField(help_text='Humidity from the weather sensor as a percentage.')),
                ('wind_speed', models.FloatField(help_text='Wind speed in m/s.')),
                ('solar_radiation', models.FloatField(help_text='Solar radiation in W/m².')),
                ('pressure_weather', models.FloatField(help_text='Atmospheric pressure in hPa.')),
                ('wind_direction', models.FloatField(help_text='Wind direction in degrees.')),
                ('temperature_weather', models.FloatField(help_text='Air temperature in Celsius.')),
                ('ec_soil_medium', models.FloatField(help_text='Electrical conductivity of soil at medium depth in dS/m.')),
                ('soil_temperature_medium', models.FloatField(help_text='Soil temperature at medium depth in Celsius.')),
                ('soil_ec_high', models.FloatField(help_text='Electrical conductivity of soil at high depth in dS/m.')),
                ('ec_soil_low', models.FloatField(help_text='Electrical conductivity of soil at low depth in dS/m.')),
                ('soil_moisture_medium', models.FloatField(help_text='Soil moisture at medium depth in percentage.')),
                ('soil_moisture_high', models.FloatField(help_text='Soil moisture at high depth in percentage.')),
                ('soil_moisture_low', models.FloatField(help_text='Soil moisture at low depth in percentage.')),
                ('ph_soil', models.FloatField(help_text='Soil pH level.')),
                ('soil_temperature_low', models.FloatField(help_text='Soil temperature at low depth in Celsius.')),
                ('soil_temperature_high', models.FloatField(help_text='Soil temperature at high depth in Celsius.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sensors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ConductivityData',
        ),
        migrations.DeleteModel(
            name='CumulData',
        ),
        migrations.RemoveField(
            model_name='dashboardsensordata',
            name='user',
        ),
        migrations.DeleteModel(
            name='PhData',
        ),
        migrations.DeleteModel(
            name='SensorData',
        ),
        migrations.RemoveField(
            model_name='stationdata',
            name='user',
        ),
        migrations.DeleteModel(
            name='TemperatureData',
        ),
        migrations.DeleteModel(
            name='DashboardSensorData',
        ),
        migrations.DeleteModel(
            name='StationData',
        ),
    ]
