# Generated by Django 4.2.16 on 2025-02-13 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0007_sensor_delete_conductivitydata_delete_cumuldata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_irrigation', models.CharField(max_length=20)),
                ('soil_ph', models.CharField(max_length=20)),
                ('soil_conductivity', models.CharField(max_length=20)),
                ('soil_moisture', models.CharField(max_length=20)),
                ('precipitation_rate', models.CharField(max_length=20)),
                ('humidity_weather', models.CharField(max_length=20)),
                ('wind_speed', models.CharField(max_length=20)),
                ('solar_radiation', models.CharField(max_length=20)),
                ('pressure_weather', models.CharField(max_length=20)),
                ('wind_direction', models.CharField(max_length=20)),
                ('temperature_weather', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_graph_names', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
