# Generated by Django 4.2.16 on 2025-02-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_alter_graphname_humidity_weather_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphname',
            name='soil_temperature',
            field=models.CharField(default='Température du sol', max_length=20),
        ),
    ]
