# Generated by Django 4.2.16 on 2025-02-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_graphname_soil_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphname',
            name='et0',
            field=models.CharField(default="Taux d'évapotranspiration", max_length=20),
        ),
    ]
