# Generated by Django 4.2.16 on 2025-02-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_graphname_et0'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphname',
            name='precipitation_humidity_rate',
            field=models.CharField(default='Taux de précipitation et humidité', max_length=20),
        ),
        migrations.AddField(
            model_name='graphname',
            name='temperature_humidity_weather',
            field=models.CharField(default="Température et humidité de l'air", max_length=20),
        ),
    ]
