# Generated by Django 4.2.16 on 2025-02-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_graphname_precipitation_humidity_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphname',
            name='Pluviometrie',
            field=models.CharField(default='Cumule de pluie tombée', max_length=20),
        ),
    ]
