# Generated by Django 4.2.16 on 2025-02-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_graphname_pluviometrie'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphname',
            name='data_table',
            field=models.CharField(default='Cumule de pluie tombée', max_length=200),
        ),
    ]
