# Generated by Django 4.2.16 on 2025-02-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0014_graphname_data_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphname',
            name='data_table',
            field=models.CharField(default='Tableau de données', max_length=20),
        ),
    ]
