# Generated by Django 4.2.16 on 2025-02-14 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0015_alter_graphname_data_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precipitation_rate_color', models.CharField(default='#3D8D7A', max_length=7)),
                ('humidity_weather_color', models.CharField(default='#2A6F97', max_length=7)),
                ('wind_speed_color', models.CharField(default='#FFB703', max_length=7)),
                ('solar_radiation_color', models.CharField(default='#E63946', max_length=7)),
                ('pressure_weather_color', models.CharField(default='#F4A261', max_length=7)),
                ('wind_direction_color', models.CharField(default='#6A0572', max_length=7)),
                ('temperature_weather_color', models.CharField(default='#E76F51', max_length=7)),
                ('ec_soil_medium_color', models.CharField(default='#2A9D8F', max_length=7)),
                ('soil_temperature_medium_color', models.CharField(default='#264653', max_length=7)),
                ('soil_ec_high_color', models.CharField(default='#8A2BE2', max_length=7)),
                ('ec_soil_low_color', models.CharField(default='#D4A373', max_length=7)),
                ('soil_moisture_medium_color', models.CharField(default='#6D597A', max_length=7)),
                ('soil_moisture_high_color', models.CharField(default='#C8553D', max_length=7)),
                ('soil_moisture_low_color', models.CharField(default='#457B9D', max_length=7)),
                ('ph_soil_color', models.CharField(default='#023E8A', max_length=7)),
                ('soil_temperature_low_color', models.CharField(default='#8D99AE', max_length=7)),
                ('soil_temperature_high_color', models.CharField(default='#E9C46A', max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sensor_colors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
