# Generated by Django 4.2.16 on 2025-02-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0016_sensorcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorcolor',
            name='et0_color',
            field=models.CharField(default='#497D74', max_length=7),
        ),
    ]
