# Generated by Django 4.2.16 on 2025-02-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0017_sensorcolor_et0_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphname',
            name='Pluviometrie',
        ),
        migrations.AlterField(
            model_name='graphname',
            name='data_table',
            field=models.CharField(default='Tableau de données', max_length=40),
        ),
        migrations.AlterField(
            model_name='graphname',
            name='et0',
            field=models.CharField(default="Taux d'évapotranspiration", max_length=40),
        ),
        migrations.AlterField(
            model_name='graphname',
            name='humidity_weather',
            field=models.CharField(default="Humidité de l'air", max_length=40),
        ),
        migrations.AlterField(
            model_name='graphname',
            name='precipitation_humidity_rate',
            field=models.CharField(default='Taux de précipitation et humidité', max_length=40),
        ),
        migrations.AlterField(
            model_name='graphname',
            name='precipitation_rate',
            field=models.CharField(default='Taux de précipitation', max_length=40),
        ),
        migrations.AlterField(
            model_name='graphname',
            name='pressure_weather',
            field=models.CharField(default='Pression atmosphérique', max_length=40),
        ),
        migrations.AlterField(
            model_name='graphname',
            name='soil_conductivity',
            field=models.CharField(default='Conductivité du sol', max_length=40),
        ),
        migrations.AlterField(
            model_name='graphname',
            name='soil_irrigation',
            field=models.CharField(default='Irrigation du sol', max_length=40),
        ),
        migrations.AlterField(
            model_name='graphname',
            name='soil_moisture',
            field=models.CharField(default='Humidité du sol', max_length=40),
        ),
        migrations.AlterField(
            model_name='graphname',
            name='soil_ph',
            field=models.CharField(default='pH du sol', max_length=40),
        ),
        migrations.AlterField(
            model_name='graphname',
            name='soil_temperature',
            field=models.CharField(default='Température du sol', max_length=40),
        ),
        migrations.AlterField(
            model_name='graphname',
            name='solar_radiation',
            field=models.CharField(default='Rayonnement solaire', max_length=40),
        ),
        migrations.AlterField(
            model_name='graphname',
            name='temperature_humidity_weather',
            field=models.CharField(default="Température et humidité de l'air", max_length=40),
        ),
        migrations.AlterField(
            model_name='graphname',
            name='temperature_weather',
            field=models.CharField(default="Température de l'air", max_length=40),
        ),
        migrations.AlterField(
            model_name='graphname',
            name='wind_direction',
            field=models.CharField(default='Direction du vent', max_length=40),
        ),
        migrations.AlterField(
            model_name='graphname',
            name='wind_speed',
            field=models.CharField(default='Vitesse du vent', max_length=40),
        ),
        migrations.AddField(
            model_name='graphname',
            name='pluviometrie',
            field=models.CharField(default='Cumule de pluie tombée', max_length=40),
        ),
    ]
