# Generated by Django 4.2.16 on 2025-02-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0018_remove_graphname_pluviometrie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='timestamp',
            field=models.DateTimeField(help_text='Timestamp when the sensor data was recorded.'),
        ),
    ]
