# Generated by Django 4.2.16 on 2025-02-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0019_alter_sensor_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='ec_soil_low',
            field=models.DecimalField(decimal_places=2, help_text='Electrical conductivity of soil at low depth in dS/m.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='ec_soil_medium',
            field=models.DecimalField(decimal_places=2, help_text='Electrical conductivity of soil at medium depth in dS/m.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='humidity_weather',
            field=models.DecimalField(decimal_places=2, help_text='Humidity from the weather sensor as a percentage.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='ph_soil',
            field=models.DecimalField(decimal_places=2, help_text='Soil pH level.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='precipitation_rate',
            field=models.DecimalField(decimal_places=2, help_text='Precipitation rate in mm/h.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='pressure_weather',
            field=models.DecimalField(decimal_places=2, help_text='Atmospheric pressure in hPa.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='soil_ec_high',
            field=models.DecimalField(decimal_places=2, help_text='Electrical conductivity of soil at high depth in dS/m.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='soil_moisture_high',
            field=models.DecimalField(decimal_places=2, help_text='Soil moisture at high depth in percentage.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='soil_moisture_low',
            field=models.DecimalField(decimal_places=2, help_text='Soil moisture at low depth in percentage.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='soil_moisture_medium',
            field=models.DecimalField(decimal_places=2, help_text='Soil moisture at medium depth in percentage.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='soil_temperature_high',
            field=models.DecimalField(decimal_places=2, help_text='Soil temperature at high depth in Celsius.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='soil_temperature_low',
            field=models.DecimalField(decimal_places=2, help_text='Soil temperature at low depth in Celsius.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='soil_temperature_medium',
            field=models.DecimalField(decimal_places=2, help_text='Soil temperature at medium depth in Celsius.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='solar_radiation',
            field=models.DecimalField(decimal_places=2, help_text='Solar radiation in W/m².', max_digits=5),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='temperature_weather',
            field=models.DecimalField(decimal_places=2, help_text='Air temperature in Celsius.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='wind_direction',
            field=models.DecimalField(decimal_places=2, help_text='Wind direction in degrees.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='wind_speed',
            field=models.DecimalField(decimal_places=2, help_text='Wind speed in m/s.', max_digits=5),
        ),
    ]
