# Generated by Django 4.2.16 on 2025-02-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0020_alter_sensor_ec_soil_low_alter_sensor_ec_soil_medium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='ec_soil_low',
            field=models.FloatField(help_text='Electrical conductivity of soil at low depth in dS/m.'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='ec_soil_medium',
            field=models.FloatField(help_text='Electrical conductivity of soil at medium depth in dS/m.'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='humidity_weather',
            field=models.FloatField(help_text='Humidity from the weather sensor as a percentage.'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='ph_soil',
            field=models.FloatField(help_text='Soil pH level.'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='precipitation_rate',
            field=models.FloatField(help_text='Precipitation rate in mm/h.'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='pressure_weather',
            field=models.FloatField(help_text='Atmospheric pressure in hPa.'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='soil_ec_high',
            field=models.FloatField(help_text='Electrical conductivity of soil at high depth in dS/m.'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='soil_moisture_high',
            field=models.FloatField(help_text='Soil moisture at high depth in percentage.'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='soil_moisture_low',
            field=models.FloatField(help_text='Soil moisture at low depth in percentage.'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='soil_moisture_medium',
            field=models.FloatField(help_text='Soil moisture at medium depth in percentage.'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='soil_temperature_high',
            field=models.FloatField(help_text='Soil temperature at high depth in Celsius.'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='soil_temperature_low',
            field=models.FloatField(help_text='Soil temperature at low depth in Celsius.'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='soil_temperature_medium',
            field=models.FloatField(help_text='Soil temperature at medium depth in Celsius.'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='solar_radiation',
            field=models.FloatField(help_text='Solar radiation in W/m².'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='temperature_weather',
            field=models.FloatField(help_text='Air temperature in Celsius.'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='wind_direction',
            field=models.FloatField(help_text='Wind direction in degrees.'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='wind_speed',
            field=models.FloatField(help_text='Wind speed in m/s.'),
        ),
    ]
