# Generated by Django 4.2.16 on 2025-03-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0021_alter_sensor_ec_soil_low_alter_sensor_ec_soil_medium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='title',
        ),
        migrations.AddField(
            model_name='alert',
            name='name',
            field=models.CharField(default='default', help_text='A brief name for the alert.', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('Pressure - Low', 'Pressure - Low'), ('Pressure - High', 'Pressure - High'), ('High Flow - High Water Usage', 'High Flow - High Water Usage'), ('Low Flow - Low Water Usage', 'Low Flow - Low Water Usage'), ('Weather Temperature - Low', 'Weather Temperature - Low'), ('Weather Temperature - High', 'Weather Temperature - High'), ('Wind Speed', 'Wind Speed'), ('Rain Fall', 'Rain Fall')], default='default', max_length=50),
            preserve_default=False,
        ),
    ]
