# Generated by Django 4.2.16 on 2025-03-05 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0022_remove_alert_title_alert_name_alert_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='danger_level',
        ),
        migrations.AddField(
            model_name='alert',
            name='condition',
            field=models.CharField(choices=[('>', 'Greater Than'), ('<', 'Less Than'), ('=', 'Equal To')], default='=', help_text='The condition for this alert (>, <, =)', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('Pressure', 'Pressure'), ('Flow', 'Flow'), ('Weather Temperature', 'Weather Temperature'), ('Wind Speed', 'Wind Speed'), ('Rain Fall', 'Rain Fall'), ('Periodic maintenance', 'Periodic maintenance'), ('EC (Electrical Conductivity)', 'EC (Electrical Conductivity)'), ('pH Level', 'pH Level'), ('Humidity', 'Humidity'), ('Soil Temperature', 'Soil Temperature')], max_length=50),
        ),
        migrations.DeleteModel(
            name='AlertsPerUser',
        ),
    ]
