# Generated by Django 4.2.16 on 2025-03-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0023_remove_alert_danger_level_alert_condition_alert_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='condition_nbr',
            field=models.DecimalField(decimal_places=0, default=50, max_digits=7),
            preserve_default=False,
        ),
    ]
