# Generated by Django 4.2.16 on 2025-04-08 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0024_alert_condition_nbr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('space', models.FloatField(help_text='The area of the zone in square meters.')),
                ('kc', models.FloatField(help_text='The crop coefficient (kc) for the zone.')),
                ('soil_type', models.CharField(choices=[('clay', 'Clay'), ('loamy', 'Loamy'), ('sandy', 'Sandy'), ('others', 'Others')], default='loamy', help_text='Type of soil in the zone.', max_length=50)),
                ('critical_moisture_threshold', models.FloatField(help_text='Critical soil moisture threshold in percentage.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='user',
        ),
        migrations.CreateModel(
            name='ZonePerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.zone')),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Sensors', to='analytics.zone'),
        ),
    ]
