# Generated by Django 4.2.16 on 2025-04-08 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0025_zone_remove_sensor_user_zoneperuser_sensor_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sensors', to='analytics.zone'),
        ),
    ]
