# Generated by Django 4.2.16 on 2025-04-08 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0026_alter_sensor_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='location',
        ),
    ]
