# Generated by Django 4.2.16 on 2025-04-09 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0027_remove_zone_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=100)),
                ('kc_january', models.FloatField(help_text='Crop coefficient for January.')),
                ('kc_february', models.FloatField(help_text='Crop coefficient for February.')),
                ('kc_march', models.FloatField(help_text='Crop coefficient for March.')),
                ('kc_april', models.FloatField(help_text='Crop coefficient for April.')),
                ('kc_may', models.FloatField(help_text='Crop coefficient for May.')),
                ('kc_june', models.FloatField(help_text='Crop coefficient for June.')),
                ('kc_july', models.FloatField(help_text='Crop coefficient for July.')),
                ('kc_august', models.FloatField(help_text='Crop coefficient for August.')),
                ('kc_september', models.FloatField(help_text='Crop coefficient for September.')),
                ('kc_october', models.FloatField(help_text='Crop coefficient for October.')),
                ('kc_november', models.FloatField(help_text='Crop coefficient for November.')),
                ('kc_december', models.FloatField(help_text='Crop coefficient for December.')),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='Sensors_per_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='water_flow_sensor',
            field=models.FloatField(default=2, help_text='Water flow sensor reading in liters per second.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='flow_rate',
            field=models.FloatField(default=1, help_text='Flow rate of water in liters per second.'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Kc_per_user_per_zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.kc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.zone')),
            ],
        ),
    ]
