# Generated by Django 4.2.16 on 2025-04-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0028_kc_sensor_user_sensor_water_flow_sensor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='water_flow_sensor',
            field=models.FloatField(blank=True, help_text='Water flow sensor reading in liters per second.', null=True),
        ),
    ]
