# Generated by Django 4.2.16 on 2025-04-20 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0029_alter_sensor_water_flow_sensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precipitation_rate', models.BooleanField(default=True)),
                ('humidity_weather', models.BooleanField(default=True)),
                ('wind_speed', models.BooleanField(default=True)),
                ('solar_radiation', models.BooleanField(default=True)),
                ('pressure_weather', models.BooleanField(default=True)),
                ('wind_direction', models.BooleanField(default=True)),
                ('temperature_weather', models.BooleanField(default=True)),
                ('ec_soil_medium', models.BooleanField(default=True)),
                ('soil_temperature_medium', models.BooleanField(default=True)),
                ('soil_ec_high', models.BooleanField(default=True)),
                ('ec_soil_low', models.BooleanField(default=True)),
                ('soil_moisture_medium', models.BooleanField(default=True)),
                ('soil_moisture_high', models.BooleanField(default=True)),
                ('soil_moisture_low', models.BooleanField(default=True)),
                ('ph_soil', models.BooleanField(default=True)),
                ('soil_temperature_low', models.BooleanField(default=True)),
                ('soil_temperature_high', models.BooleanField(default=True)),
                ('water_flow_sensor', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveSensorPerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analytics.activesensor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sensor_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
