# Generated by Django 4.2.16 on 2025-04-20 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0030_activesensor_activesensorperuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activesensor',
            old_name='ec_soil_low',
            new_name='ec_soil_low_status',
        ),
        migrations.RenameField(
            model_name='activesensor',
            old_name='ec_soil_medium',
            new_name='ec_soil_medium_status',
        ),
        migrations.RenameField(
            model_name='activesensor',
            old_name='humidity_weather',
            new_name='humidity_weather_status',
        ),
        migrations.RenameField(
            model_name='activesensor',
            old_name='ph_soil',
            new_name='ph_soil_status',
        ),
        migrations.RenameField(
            model_name='activesensor',
            old_name='precipitation_rate',
            new_name='precipitation_rate_status',
        ),
        migrations.RenameField(
            model_name='activesensor',
            old_name='pressure_weather',
            new_name='pressure_weather_status',
        ),
        migrations.RenameField(
            model_name='activesensor',
            old_name='soil_ec_high',
            new_name='soil_ec_high_status',
        ),
        migrations.RenameField(
            model_name='activesensor',
            old_name='soil_moisture_high',
            new_name='soil_moisture_high_status',
        ),
        migrations.RenameField(
            model_name='activesensor',
            old_name='soil_moisture_low',
            new_name='soil_moisture_low_status',
        ),
        migrations.RenameField(
            model_name='activesensor',
            old_name='soil_moisture_medium',
            new_name='soil_moisture_medium_status',
        ),
        migrations.RenameField(
            model_name='activesensor',
            old_name='soil_temperature_high',
            new_name='soil_temperature_high_status',
        ),
        migrations.RenameField(
            model_name='activesensor',
            old_name='soil_temperature_low',
            new_name='soil_temperature_low_status',
        ),
        migrations.RenameField(
            model_name='activesensor',
            old_name='soil_temperature_medium',
            new_name='soil_temperature_medium_status',
        ),
        migrations.RenameField(
            model_name='activesensor',
            old_name='solar_radiation',
            new_name='solar_radiation_status',
        ),
        migrations.RenameField(
            model_name='activesensor',
            old_name='temperature_weather',
            new_name='temperature_weather_status',
        ),
        migrations.RenameField(
            model_name='activesensor',
            old_name='water_flow_sensor',
            new_name='water_flow_sensor_status',
        ),
        migrations.RenameField(
            model_name='activesensor',
            old_name='wind_direction',
            new_name='wind_direction_status',
        ),
        migrations.RenameField(
            model_name='activesensor',
            old_name='wind_speed',
            new_name='wind_speed_status',
        ),
    ]
