# Generated by Django 4.2.16 on 2025-04-20 20:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0031_rename_ec_soil_low_activesensor_ec_soil_low_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActiveSensor',
            new_name='ActiveGraph',
        ),
        migrations.RenameModel(
            old_name='ActiveSensorPerUser',
            new_name='ActiveGraphPerUser',
        ),
    ]
