# Generated by Django 4.2.16 on 2025-04-20 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0032_rename_activesensor_activegraph_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activegraph',
            old_name='ec_soil_low_status',
            new_name='conductivity_status',
        ),
        migrations.RenameField(
            model_name='activegraph',
            old_name='ec_soil_medium_status',
            new_name='et0_status',
        ),
        migrations.RenameField(
            model_name='activegraph',
            old_name='humidity_weather_status',
            new_name='evapotranspiration_status',
        ),
        migrations.RenameField(
            model_name='activegraph',
            old_name='ph_soil_status',
            new_name='irrigation_status',
        ),
        migrations.RenameField(
            model_name='activegraph',
            old_name='precipitation_rate_status',
            new_name='ph_status',
        ),
        migrations.RenameField(
            model_name='activegraph',
            old_name='pressure_weather_status',
            new_name='rainfall_humidity_status',
        ),
        migrations.RenameField(
            model_name='activegraph',
            old_name='soil_ec_high_status',
            new_name='rainfall_status',
        ),
        migrations.RenameField(
            model_name='activegraph',
            old_name='soil_moisture_high_status',
            new_name='temperature_humidity_status',
        ),
        migrations.RenameField(
            model_name='activegraph',
            old_name='soil_moisture_low_status',
            new_name='temperature_status',
        ),
        migrations.RenameField(
            model_name='activegraph',
            old_name='soil_moisture_medium_status',
            new_name='wind_status',
        ),
        migrations.RemoveField(
            model_name='activegraph',
            name='soil_temperature_high_status',
        ),
        migrations.RemoveField(
            model_name='activegraph',
            name='soil_temperature_low_status',
        ),
        migrations.RemoveField(
            model_name='activegraph',
            name='soil_temperature_medium_status',
        ),
        migrations.RemoveField(
            model_name='activegraph',
            name='temperature_weather_status',
        ),
        migrations.RemoveField(
            model_name='activegraph',
            name='water_flow_sensor_status',
        ),
    ]
