# Generated by Django 4.2.16 on 2025-04-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0033_rename_ec_soil_low_status_activegraph_conductivity_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activegraph',
            name='conductivity_status',
        ),
        migrations.RemoveField(
            model_name='activegraph',
            name='evapotranspiration_status',
        ),
        migrations.RemoveField(
            model_name='activegraph',
            name='irrigation_status',
        ),
        migrations.RemoveField(
            model_name='activegraph',
            name='ph_status',
        ),
        migrations.RemoveField(
            model_name='activegraph',
            name='rainfall_humidity_status',
        ),
        migrations.RemoveField(
            model_name='activegraph',
            name='rainfall_status',
        ),
        migrations.RemoveField(
            model_name='activegraph',
            name='temperature_humidity_status',
        ),
        migrations.RemoveField(
            model_name='activegraph',
            name='temperature_status',
        ),
        migrations.RemoveField(
            model_name='activegraph',
            name='wind_status',
        ),
        migrations.AddField(
            model_name='activegraph',
            name='data_table_status',
            field=models.BooleanField(default=True, help_text='Tableau de données'),
        ),
        migrations.AddField(
            model_name='activegraph',
            name='humidity_weather_status',
            field=models.BooleanField(default=True, help_text="Humidité de l'air"),
        ),
        migrations.AddField(
            model_name='activegraph',
            name='pluviometrie_status',
            field=models.BooleanField(default=True, help_text='Cumule de pluie tombée'),
        ),
        migrations.AddField(
            model_name='activegraph',
            name='precipitation_humidity_rate_status',
            field=models.BooleanField(default=True, help_text='Taux de précipitation et humidité'),
        ),
        migrations.AddField(
            model_name='activegraph',
            name='precipitation_rate_status',
            field=models.BooleanField(default=True, help_text='Taux de précipitation'),
        ),
        migrations.AddField(
            model_name='activegraph',
            name='pressure_weather_status',
            field=models.BooleanField(default=True, help_text='Pression atmosphérique'),
        ),
        migrations.AddField(
            model_name='activegraph',
            name='soil_conductivity_status',
            field=models.BooleanField(default=True, help_text='Conductivité du sol'),
        ),
        migrations.AddField(
            model_name='activegraph',
            name='soil_irrigation_status',
            field=models.BooleanField(default=True, help_text='Irrigation du sol'),
        ),
        migrations.AddField(
            model_name='activegraph',
            name='soil_moisture_status',
            field=models.BooleanField(default=True, help_text='Humidité du sol'),
        ),
        migrations.AddField(
            model_name='activegraph',
            name='soil_ph_status',
            field=models.BooleanField(default=True, help_text='pH du sol'),
        ),
        migrations.AddField(
            model_name='activegraph',
            name='soil_temperature_status',
            field=models.BooleanField(default=True, help_text='Température du sol'),
        ),
        migrations.AddField(
            model_name='activegraph',
            name='temperature_humidity_weather_status',
            field=models.BooleanField(default=True, help_text="Température et humidité de l'air"),
        ),
        migrations.AddField(
            model_name='activegraph',
            name='temperature_weather_status',
            field=models.BooleanField(default=True, help_text="Température de l'air"),
        ),
        migrations.AlterField(
            model_name='activegraph',
            name='et0_status',
            field=models.BooleanField(default=True, help_text="Taux d'évapotranspiration"),
        ),
        migrations.AlterField(
            model_name='activegraph',
            name='solar_radiation_status',
            field=models.BooleanField(default=True, help_text='Rayonnement solaire'),
        ),
        migrations.AlterField(
            model_name='activegraph',
            name='wind_direction_status',
            field=models.BooleanField(default=True, help_text='Direction du vent'),
        ),
        migrations.AlterField(
            model_name='activegraph',
            name='wind_speed_status',
            field=models.BooleanField(default=True, help_text='Vitesse du vent'),
        ),
    ]
