# Generated by Django 4.2.16 on 2025-04-21 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0034_remove_activegraph_conductivity_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activegraph',
            name='humidity_weather_status',
        ),
        migrations.RemoveField(
            model_name='activegraph',
            name='precipitation_rate_status',
        ),
        migrations.RemoveField(
            model_name='activegraph',
            name='pressure_weather_status',
        ),
        migrations.RemoveField(
            model_name='activegraph',
            name='temperature_weather_status',
        ),
    ]
