# Generated by Django 4.2.16 on 2025-04-27 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0035_remove_activegraph_humidity_weather_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcSalinitySensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('courbe_color', models.CharField(default='#000000', max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('value', models.FloatField(blank=True, help_text='EC and salinity measurement.', null=True)),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ec_salinity_sensors_per_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ECSoilLow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('courbe_color', models.CharField(default='#000000', max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('value', models.FloatField(help_text='Electrical conductivity of soil at low depth in dS/m.')),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ec_soil_low_per_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ECSoilMedium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('courbe_color', models.CharField(default='#000000', max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('value', models.FloatField(help_text='Electrical conductivity of soil at medium depth in dS/m.')),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ec_soil_medium_per_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ElectricityConsumptionSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('courbe_color', models.CharField(default='#000000', max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('value', models.FloatField(blank=True, help_text='Electricity consumption reading.', null=True)),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electricity_consumption_sensors_per_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FruitSizeSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('courbe_color', models.CharField(default='#000000', max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('value', models.FloatField(blank=True, help_text='Fruit size measurement.', null=True)),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fruit_size_sensors_per_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HumidityWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('courbe_color', models.CharField(default='#000000', max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('value', models.FloatField(help_text='Humidity from the weather sensor as a percentage.')),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='humidity_weather_per_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KcPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('kc_value', models.FloatField(help_text='Kc value for this period.')),
            ],
        ),
        migrations.CreateModel(
            name='KcPeriodAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LargeFruitDiameterSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('courbe_color', models.CharField(default='#000000', max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('value', models.FloatField(blank=True, help_text='Large fruit diameter size.', null=True)),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='large_fruit_diameter_sensors_per_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeafMoistureSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('courbe_color', models.CharField(default='#000000', max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('value', models.FloatField(blank=True, help_text='Leaf moisture percentage.', null=True)),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaf_moisture_sensors_per_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MultiDepthSoilMoistureSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('courbe_color', models.CharField(default='#000000', max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('value', models.FloatField(blank=True, help_text='Multi-depth soil moisture percentage.', null=True)),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_depth_soil_moisture_sensors_per_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NpkSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('courbe_color', models.CharField(default='#000000', max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('value', models.FloatField(blank=True, help_text='Soil nutrient NPK reading.', null=True)),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npk_sensors_per_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhSoil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('courbe_color', models.CharField(default='#000000', max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('value', models.FloatField(help_text='Soil pH level.')),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ph_soil_per_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhWaterSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('courbe_color', models.CharField(default='#000000', max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('value', models.FloatField(blank=True, help_text='pH level of water.', null=True)),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ph_water_sensors_per_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrecipitationRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('courbe_color', models.CharField(default='#000000', max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('value', models.FloatField(help_text='Precipitation rate in mm/h.')),
                ('timestamp', models.DateTimeField(help_text='Timestamp when the sensor data was recorded.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precipitation_rates_per_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PressureWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('courbe_color', models.CharField(default='#000000', max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('value', models.FloatField(help_text='Atmospheric pressure in hPa.')),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pressure_weather_per_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoilECHigh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('courbe_color', models.CharField(default='#000000', max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('value', models.FloatField(help_text='Electrical conductivity of soil at high depth in dS/m.')),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_ec_high_per_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoilMoistureHigh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('courbe_color', models.CharField(default='#000000', max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('value', models.FloatField(help_text='Soil moisture at high depth in percentage.')),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_moisture_high_per_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoilMoistureLow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('courbe_color', models.CharField(default='#000000', max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('value', models.FloatField(help_text='Soil moisture at low depth in percentage.')),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_moisture_low_per_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoilMoistureMedium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('courbe_color', models.CharField(default='#000000', max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('value', models.FloatField(help_text='Soil moisture at medium depth in percentage.')),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_moisture_medium_per_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoilSalinityConductivityIntegratedSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('courbe_color', models.CharField(default='#000000', max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('value', models.FloatField(blank=True, help_text='Soil salinity conductivity value.', null=True)),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_salinity_conductivity_integrated_sensors_per_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoilTemperatureHigh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('courbe_color', models.CharField(default='#000000', max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('value', models.FloatField(help_text='Soil temperature at high depth in Celsius.')),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_temperature_high_per_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoilTemperatureLow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('courbe_color', models.CharField(default='#000000', max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('value', models.FloatField(help_text='Soil temperature at low depth in Celsius.')),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_temperature_low_per_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoilTemperatureMedium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('courbe_color', models.CharField(default='#000000', max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('value', models.FloatField(help_text='Soil temperature at medium depth in Celsius.')),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_temperature_medium_per_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolarRadiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('courbe_color', models.CharField(default='#000000', max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('value', models.FloatField(help_text='Solar radiation in W/m².')),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solar_radiations_per_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('courbe_color', models.CharField(default='#000000', max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('value', models.FloatField(help_text='Air temperature in Celsius.')),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_weather_per_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WaterECSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('courbe_color', models.CharField(default='#000000', max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('value', models.FloatField(blank=True, help_text='Water EC sensor reading in μS/cm.', null=True)),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_ec_sensors_per_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WaterFlowSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('courbe_color', models.CharField(default='#000000', max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('value', models.FloatField(blank=True, help_text='Water flow sensor reading in liters per second.', null=True)),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_flow_sensors_per_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WaterLevelSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('courbe_color', models.CharField(default='#000000', max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('value', models.FloatField(blank=True, help_text='Water level in the tank or river.', null=True)),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_level_sensors_per_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WindDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('courbe_color', models.CharField(default='#000000', max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('value', models.FloatField(help_text='Wind direction in degrees.')),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wind_directions_per_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WindSpeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('courbe_color', models.CharField(default='#000000', max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('value', models.FloatField(help_text='Wind speed in m/s.')),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wind_speeds_per_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='activegraphperuser',
            name='active_sensor',
        ),
        migrations.RemoveField(
            model_name='activegraphperuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='graphname',
            name='user',
        ),
        migrations.RemoveField(
            model_name='kc_per_user_per_zone',
            name='kc',
        ),
        migrations.RemoveField(
            model_name='kc_per_user_per_zone',
            name='user',
        ),
        migrations.RemoveField(
            model_name='kc_per_user_per_zone',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='sensorcolor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='kc',
            name='kc_april',
        ),
        migrations.RemoveField(
            model_name='kc',
            name='kc_august',
        ),
        migrations.RemoveField(
            model_name='kc',
            name='kc_december',
        ),
        migrations.RemoveField(
            model_name='kc',
            name='kc_february',
        ),
        migrations.RemoveField(
            model_name='kc',
            name='kc_january',
        ),
        migrations.RemoveField(
            model_name='kc',
            name='kc_july',
        ),
        migrations.RemoveField(
            model_name='kc',
            name='kc_june',
        ),
        migrations.RemoveField(
            model_name='kc',
            name='kc_march',
        ),
        migrations.RemoveField(
            model_name='kc',
            name='kc_may',
        ),
        migrations.RemoveField(
            model_name='kc',
            name='kc_november',
        ),
        migrations.RemoveField(
            model_name='kc',
            name='kc_october',
        ),
        migrations.RemoveField(
            model_name='kc',
            name='kc_september',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='flow_rate',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='kc',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='soil_type',
        ),
        migrations.AddField(
            model_name='kc',
            name='name',
            field=models.CharField(default='', help_text='Name of the KC data set.', max_length=100),
        ),
        migrations.AddField(
            model_name='kc',
            name='number_of_periods',
            field=models.IntegerField(default=2, help_text='Number of periods for which KC values are provided.'),
        ),
        migrations.AddField(
            model_name='kc',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kc_per_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kc',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kc_values', to='analytics.zone'),
        ),
        migrations.AddField(
            model_name='zone',
            name='irrigation_water_quantity',
            field=models.FloatField(default=100, help_text='Irrigation water quantity in liters.'),
        ),
        migrations.AddField(
            model_name='zone',
            name='pomp_flow_rate',
            field=models.FloatField(default=100, help_text='Pump flow rate in liters per second.'),
        ),
        migrations.AddField(
            model_name='zone',
            name='soil_param_1',
            field=models.FloatField(default=50, help_text='First soil identification parameter.'),
        ),
        migrations.AddField(
            model_name='zone',
            name='soil_param_2',
            field=models.FloatField(default=50, help_text='Second soil identification parameter.'),
        ),
        migrations.AddField(
            model_name='zone',
            name='soil_param_3',
            field=models.FloatField(default=50, help_text='Third soil identification parameter.'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='critical_moisture_threshold',
            field=models.FloatField(help_text='Critical soil moisture threshold in %.'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='space',
            field=models.FloatField(help_text='Area in square meters.'),
        ),
        migrations.DeleteModel(
            name='ActiveGraph',
        ),
        migrations.DeleteModel(
            name='ActiveGraphPerUser',
        ),
        migrations.DeleteModel(
            name='GraphName',
        ),
        migrations.DeleteModel(
            name='Kc_per_user_per_zone',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
        migrations.DeleteModel(
            name='SensorColor',
        ),
        migrations.AddField(
            model_name='windspeed',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wind_speeds', to='analytics.zone'),
        ),
        migrations.AddField(
            model_name='winddirection',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wind_directions', to='analytics.zone'),
        ),
        migrations.AddField(
            model_name='waterlevelsensor',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_level_sensors', to='analytics.zone'),
        ),
        migrations.AddField(
            model_name='waterflowsensor',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_flow_sensors', to='analytics.zone'),
        ),
        migrations.AddField(
            model_name='waterecsensor',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_ec_sensors', to='analytics.zone'),
        ),
        migrations.AddField(
            model_name='temperatureweather',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_weather', to='analytics.zone'),
        ),
        migrations.AddField(
            model_name='solarradiation',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solar_radiations', to='analytics.zone'),
        ),
        migrations.AddField(
            model_name='soiltemperaturemedium',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_temperature_medium', to='analytics.zone'),
        ),
        migrations.AddField(
            model_name='soiltemperaturelow',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_temperature_low', to='analytics.zone'),
        ),
        migrations.AddField(
            model_name='soiltemperaturehigh',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_temperature_high', to='analytics.zone'),
        ),
        migrations.AddField(
            model_name='soilsalinityconductivityintegratedsensor',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_salinity_conductivity_integrated_sensors', to='analytics.zone'),
        ),
        migrations.AddField(
            model_name='soilmoisturemedium',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_moisture_medium', to='analytics.zone'),
        ),
        migrations.AddField(
            model_name='soilmoisturelow',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_moisture_low', to='analytics.zone'),
        ),
        migrations.AddField(
            model_name='soilmoisturehigh',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_moisture_high', to='analytics.zone'),
        ),
        migrations.AddField(
            model_name='soilechigh',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_ec_high', to='analytics.zone'),
        ),
        migrations.AddField(
            model_name='pressureweather',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pressure_weather', to='analytics.zone'),
        ),
        migrations.AddField(
            model_name='precipitationrate',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precipitation_rates', to='analytics.zone'),
        ),
        migrations.AddField(
            model_name='phwatersensor',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ph_water_sensors', to='analytics.zone'),
        ),
        migrations.AddField(
            model_name='phsoil',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ph_soil', to='analytics.zone'),
        ),
        migrations.AddField(
            model_name='npksensor',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npk_sensors', to='analytics.zone'),
        ),
        migrations.AddField(
            model_name='multidepthsoilmoisturesensor',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_depth_soil_moisture_sensors', to='analytics.zone'),
        ),
        migrations.AddField(
            model_name='leafmoisturesensor',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaf_moisture_sensors', to='analytics.zone'),
        ),
        migrations.AddField(
            model_name='largefruitdiametersensor',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='large_fruit_diameter_sensors', to='analytics.zone'),
        ),
        migrations.AddField(
            model_name='kcperiodassignment',
            name='kc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='analytics.kc'),
        ),
        migrations.AddField(
            model_name='kcperiodassignment',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kc_assignments', to='analytics.kcperiod'),
        ),
        migrations.AddField(
            model_name='humidityweather',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='humidity_weather', to='analytics.zone'),
        ),
        migrations.AddField(
            model_name='fruitsizesensor',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fruit_size_sensors', to='analytics.zone'),
        ),
        migrations.AddField(
            model_name='electricityconsumptionsensor',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electricity_consumption_sensors', to='analytics.zone'),
        ),
        migrations.AddField(
            model_name='ecsoilmedium',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ec_soil_medium', to='analytics.zone'),
        ),
        migrations.AddField(
            model_name='ecsoillow',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ec_soil_low', to='analytics.zone'),
        ),
        migrations.AddField(
            model_name='ecsalinitysensor',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ec_salinity_sensors', to='analytics.zone'),
        ),
    ]
