# Generated by Django 4.2.16 on 2025-04-28 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0037_notification_user_delete_notificationsperuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZonePerUser',
        ),
    ]
