# Generated by Django 4.2.16 on 2025-04-30 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0038_delete_zoneperuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecsalinitysensor',
            name='courbe_color',
        ),
        migrations.RemoveField(
            model_name='ecsalinitysensor',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='ecsalinitysensor',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='ecsalinitysensor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ecsoillow',
            name='courbe_color',
        ),
        migrations.RemoveField(
            model_name='ecsoillow',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='ecsoillow',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='ecsoillow',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ecsoilmedium',
            name='courbe_color',
        ),
        migrations.RemoveField(
            model_name='ecsoilmedium',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='ecsoilmedium',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='ecsoilmedium',
            name='name',
        ),
        migrations.RemoveField(
            model_name='electricityconsumptionsensor',
            name='courbe_color',
        ),
        migrations.RemoveField(
            model_name='electricityconsumptionsensor',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='electricityconsumptionsensor',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='electricityconsumptionsensor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='fruitsizesensor',
            name='courbe_color',
        ),
        migrations.RemoveField(
            model_name='fruitsizesensor',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='fruitsizesensor',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='fruitsizesensor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='humidityweather',
            name='courbe_color',
        ),
        migrations.RemoveField(
            model_name='humidityweather',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='humidityweather',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='humidityweather',
            name='name',
        ),
        migrations.RemoveField(
            model_name='largefruitdiametersensor',
            name='courbe_color',
        ),
        migrations.RemoveField(
            model_name='largefruitdiametersensor',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='largefruitdiametersensor',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='largefruitdiametersensor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='leafmoisturesensor',
            name='courbe_color',
        ),
        migrations.RemoveField(
            model_name='leafmoisturesensor',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='leafmoisturesensor',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='leafmoisturesensor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='multidepthsoilmoisturesensor',
            name='courbe_color',
        ),
        migrations.RemoveField(
            model_name='multidepthsoilmoisturesensor',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='multidepthsoilmoisturesensor',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='multidepthsoilmoisturesensor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='npksensor',
            name='courbe_color',
        ),
        migrations.RemoveField(
            model_name='npksensor',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='npksensor',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='npksensor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='phsoil',
            name='courbe_color',
        ),
        migrations.RemoveField(
            model_name='phsoil',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='phsoil',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='phsoil',
            name='name',
        ),
        migrations.RemoveField(
            model_name='phwatersensor',
            name='courbe_color',
        ),
        migrations.RemoveField(
            model_name='phwatersensor',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='phwatersensor',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='phwatersensor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='precipitationrate',
            name='courbe_color',
        ),
        migrations.RemoveField(
            model_name='precipitationrate',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='precipitationrate',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='precipitationrate',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pressureweather',
            name='courbe_color',
        ),
        migrations.RemoveField(
            model_name='pressureweather',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='pressureweather',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='pressureweather',
            name='name',
        ),
        migrations.RemoveField(
            model_name='soilechigh',
            name='courbe_color',
        ),
        migrations.RemoveField(
            model_name='soilechigh',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='soilechigh',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='soilechigh',
            name='name',
        ),
        migrations.RemoveField(
            model_name='soilmoisturehigh',
            name='courbe_color',
        ),
        migrations.RemoveField(
            model_name='soilmoisturehigh',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='soilmoisturehigh',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='soilmoisturehigh',
            name='name',
        ),
        migrations.RemoveField(
            model_name='soilmoisturelow',
            name='courbe_color',
        ),
        migrations.RemoveField(
            model_name='soilmoisturelow',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='soilmoisturelow',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='soilmoisturelow',
            name='name',
        ),
        migrations.RemoveField(
            model_name='soilmoisturemedium',
            name='courbe_color',
        ),
        migrations.RemoveField(
            model_name='soilmoisturemedium',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='soilmoisturemedium',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='soilmoisturemedium',
            name='name',
        ),
        migrations.RemoveField(
            model_name='soilsalinityconductivityintegratedsensor',
            name='courbe_color',
        ),
        migrations.RemoveField(
            model_name='soilsalinityconductivityintegratedsensor',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='soilsalinityconductivityintegratedsensor',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='soilsalinityconductivityintegratedsensor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='soiltemperaturehigh',
            name='courbe_color',
        ),
        migrations.RemoveField(
            model_name='soiltemperaturehigh',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='soiltemperaturehigh',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='soiltemperaturehigh',
            name='name',
        ),
        migrations.RemoveField(
            model_name='soiltemperaturelow',
            name='courbe_color',
        ),
        migrations.RemoveField(
            model_name='soiltemperaturelow',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='soiltemperaturelow',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='soiltemperaturelow',
            name='name',
        ),
        migrations.RemoveField(
            model_name='soiltemperaturemedium',
            name='courbe_color',
        ),
        migrations.RemoveField(
            model_name='soiltemperaturemedium',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='soiltemperaturemedium',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='soiltemperaturemedium',
            name='name',
        ),
        migrations.RemoveField(
            model_name='solarradiation',
            name='courbe_color',
        ),
        migrations.RemoveField(
            model_name='solarradiation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='solarradiation',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='solarradiation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='temperatureweather',
            name='courbe_color',
        ),
        migrations.RemoveField(
            model_name='temperatureweather',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='temperatureweather',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='temperatureweather',
            name='name',
        ),
        migrations.RemoveField(
            model_name='waterecsensor',
            name='courbe_color',
        ),
        migrations.RemoveField(
            model_name='waterecsensor',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='waterecsensor',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='waterecsensor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='waterflowsensor',
            name='courbe_color',
        ),
        migrations.RemoveField(
            model_name='waterflowsensor',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='waterflowsensor',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='waterflowsensor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='waterlevelsensor',
            name='courbe_color',
        ),
        migrations.RemoveField(
            model_name='waterlevelsensor',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='waterlevelsensor',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='waterlevelsensor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='winddirection',
            name='courbe_color',
        ),
        migrations.RemoveField(
            model_name='winddirection',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='winddirection',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='winddirection',
            name='name',
        ),
        migrations.RemoveField(
            model_name='windspeed',
            name='courbe_color',
        ),
        migrations.RemoveField(
            model_name='windspeed',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='windspeed',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='windspeed',
            name='name',
        ),
        migrations.AlterField(
            model_name='ecsoillow',
            name='value',
            field=models.FloatField(blank=True, help_text='Electrical conductivity of soil at low depth in dS/m.', null=True),
        ),
        migrations.AlterField(
            model_name='ecsoilmedium',
            name='value',
            field=models.FloatField(blank=True, help_text='Electrical conductivity of soil at medium depth in dS/m.', null=True),
        ),
        migrations.AlterField(
            model_name='humidityweather',
            name='value',
            field=models.FloatField(blank=True, help_text='Humidity from the weather sensor as a percentage.', null=True),
        ),
        migrations.AlterField(
            model_name='phsoil',
            name='value',
            field=models.FloatField(blank=True, help_text='Soil pH level.', null=True),
        ),
        migrations.AlterField(
            model_name='precipitationrate',
            name='value',
            field=models.FloatField(blank=True, help_text='Precipitation rate in mm/h.', null=True),
        ),
        migrations.AlterField(
            model_name='pressureweather',
            name='value',
            field=models.FloatField(blank=True, help_text='Atmospheric pressure in hPa.', null=True),
        ),
        migrations.AlterField(
            model_name='soilechigh',
            name='value',
            field=models.FloatField(blank=True, help_text='Electrical conductivity of soil at high depth in dS/m.', null=True),
        ),
        migrations.AlterField(
            model_name='soilmoisturehigh',
            name='value',
            field=models.FloatField(blank=True, help_text='Soil moisture at high depth in percentage.', null=True),
        ),
        migrations.AlterField(
            model_name='soilmoisturelow',
            name='value',
            field=models.FloatField(blank=True, help_text='Soil moisture at low depth in percentage.', null=True),
        ),
        migrations.AlterField(
            model_name='soilmoisturemedium',
            name='value',
            field=models.FloatField(blank=True, help_text='Soil moisture at medium depth in percentage.', null=True),
        ),
        migrations.AlterField(
            model_name='soiltemperaturehigh',
            name='value',
            field=models.FloatField(blank=True, help_text='Soil temperature at high depth in Celsius.', null=True),
        ),
        migrations.AlterField(
            model_name='soiltemperaturelow',
            name='value',
            field=models.FloatField(blank=True, help_text='Soil temperature at low depth in Celsius.', null=True),
        ),
        migrations.AlterField(
            model_name='soiltemperaturemedium',
            name='value',
            field=models.FloatField(blank=True, help_text='Soil temperature at medium depth in Celsius.', null=True),
        ),
        migrations.AlterField(
            model_name='solarradiation',
            name='value',
            field=models.FloatField(blank=True, help_text='Solar radiation in W/m².', null=True),
        ),
        migrations.AlterField(
            model_name='temperatureweather',
            name='value',
            field=models.FloatField(blank=True, help_text='Air temperature in Celsius.', null=True),
        ),
        migrations.AlterField(
            model_name='winddirection',
            name='value',
            field=models.FloatField(blank=True, help_text='Wind direction in degrees.', null=True),
        ),
        migrations.AlterField(
            model_name='windspeed',
            name='value',
            field=models.FloatField(blank=True, help_text='Wind speed in m/s.', null=True),
        ),
        migrations.CreateModel(
            name='SensorLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precipitation_rate_longitude', models.FloatField()),
                ('precipitation_rate_latitude', models.FloatField()),
                ('humidity_weather_longitude', models.FloatField()),
                ('humidity_weather_latitude', models.FloatField()),
                ('wind_speed_longitude', models.FloatField()),
                ('wind_speed_latitude', models.FloatField()),
                ('solar_radiation_longitude', models.FloatField()),
                ('solar_radiation_latitude', models.FloatField()),
                ('pressure_weather_longitude', models.FloatField()),
                ('pressure_weather_latitude', models.FloatField()),
                ('wind_direction_longitude', models.FloatField()),
                ('wind_direction_latitude', models.FloatField()),
                ('temperature_weather_longitude', models.FloatField()),
                ('temperature_weather_latitude', models.FloatField()),
                ('et0_longitude', models.FloatField()),
                ('et0_latitude', models.FloatField()),
                ('ec_soil_medium_longitude', models.FloatField()),
                ('ec_soil_medium_latitude', models.FloatField()),
                ('soil_temperature_medium_longitude', models.FloatField()),
                ('soil_temperature_medium_latitude', models.FloatField()),
                ('soil_ec_high_longitude', models.FloatField()),
                ('soil_ec_high_latitude', models.FloatField()),
                ('ec_soil_low_longitude', models.FloatField()),
                ('ec_soil_low_latitude', models.FloatField()),
                ('soil_moisture_medium_longitude', models.FloatField()),
                ('soil_moisture_medium_latitude', models.FloatField()),
                ('soil_moisture_high_longitude', models.FloatField()),
                ('soil_moisture_high_latitude', models.FloatField()),
                ('soil_moisture_low_longitude', models.FloatField()),
                ('soil_moisture_low_latitude', models.FloatField()),
                ('ph_soil_longitude', models.FloatField()),
                ('ph_soil_latitude', models.FloatField()),
                ('soil_temperature_low_longitude', models.FloatField()),
                ('soil_temperature_low_latitude', models.FloatField()),
                ('soil_temperature_high_longitude', models.FloatField()),
                ('soil_temperature_high_latitude', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sensor_locations', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_sensor_locations', to='analytics.zone')),
            ],
        ),
        migrations.CreateModel(
            name='SensorColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precipitation_rate_color', models.CharField(default='#3D8D7A', max_length=7)),
                ('humidity_weather_color', models.CharField(default='#2A6F97', max_length=7)),
                ('wind_speed_color', models.CharField(default='#FFB703', max_length=7)),
                ('solar_radiation_color', models.CharField(default='#E63946', max_length=7)),
                ('pressure_weather_color', models.CharField(default='#F4A261', max_length=7)),
                ('wind_direction_color', models.CharField(default='#6A0572', max_length=7)),
                ('temperature_weather_color', models.CharField(default='#E76F51', max_length=7)),
                ('et0_color', models.CharField(default='#497D74', max_length=7)),
                ('ec_soil_medium_color', models.CharField(default='#2A9D8F', max_length=7)),
                ('soil_temperature_medium_color', models.CharField(default='#264653', max_length=7)),
                ('soil_ec_high_color', models.CharField(default='#8A2BE2', max_length=7)),
                ('ec_soil_low_color', models.CharField(default='#D4A373', max_length=7)),
                ('soil_moisture_medium_color', models.CharField(default='#6D597A', max_length=7)),
                ('soil_moisture_high_color', models.CharField(default='#C8553D', max_length=7)),
                ('soil_moisture_low_color', models.CharField(default='#457B9D', max_length=7)),
                ('ph_soil_color', models.CharField(default='#023E8A', max_length=7)),
                ('soil_temperature_low_color', models.CharField(default='#8D99AE', max_length=7)),
                ('soil_temperature_high_color', models.CharField(default='#E9C46A', max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sensor_colors', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_sensor_colors', to='analytics.zone')),
            ],
        ),
        migrations.CreateModel(
            name='GraphName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_irrigation', models.CharField(default='Irrigation du sol', max_length=40)),
                ('soil_ph', models.CharField(default='pH du sol', max_length=40)),
                ('soil_conductivity', models.CharField(default='Conductivité du sol', max_length=40)),
                ('soil_moisture', models.CharField(default='Humidité du sol', max_length=40)),
                ('soil_temperature', models.CharField(default='Température du sol', max_length=40)),
                ('et0', models.CharField(default="Taux d'évapotranspiration", max_length=40)),
                ('precipitation_rate', models.CharField(default='Taux de précipitation', max_length=40)),
                ('wind_speed', models.CharField(default='Vitesse du vent', max_length=40)),
                ('solar_radiation', models.CharField(default='Rayonnement solaire', max_length=40)),
                ('pressure_weather', models.CharField(default='Pression atmosphérique', max_length=40)),
                ('wind_direction', models.CharField(default='Direction du vent', max_length=40)),
                ('humidity_weather', models.CharField(default="Humidité de l'air", max_length=40)),
                ('temperature_weather', models.CharField(default="Température de l'air", max_length=40)),
                ('temperature_humidity_weather', models.CharField(default="Température et humidité de l'air", max_length=40)),
                ('precipitation_humidity_rate', models.CharField(default='Taux de précipitation et humidité', max_length=40)),
                ('pluviometrie', models.CharField(default='Cumule de pluie tombée', max_length=40)),
                ('data_table', models.CharField(default='Tableau de données', max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_graph_names', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_graph_names', to='analytics.zone')),
            ],
        ),
    ]
