# Generated by Django 4.2.16 on 2025-04-30 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0039_remove_ecsalinitysensor_courbe_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_irrigation_status', models.BooleanField(default=True, help_text='Irrigation du sol')),
                ('soil_ph_status', models.BooleanField(default=True, help_text='pH du sol')),
                ('soil_conductivity_status', models.BooleanField(default=True, help_text='Conductivité du sol')),
                ('soil_moisture_status', models.BooleanField(default=True, help_text='Humidité du sol')),
                ('soil_temperature_status', models.BooleanField(default=True, help_text='Température du sol')),
                ('et0_status', models.BooleanField(default=True, help_text="Taux d'évapotranspiration")),
                ('wind_speed_status', models.BooleanField(default=True, help_text='Vitesse du vent')),
                ('solar_radiation_status', models.BooleanField(default=True, help_text='Rayonnement solaire')),
                ('wind_direction_status', models.BooleanField(default=True, help_text='Direction du vent')),
                ('temperature_humidity_weather_status', models.BooleanField(default=True, help_text="Température et humidité de l'air")),
                ('precipitation_humidity_rate_status', models.BooleanField(default=True, help_text='Taux de précipitation et humidité')),
                ('pluviometrie_status', models.BooleanField(default=True, help_text='Cumule de pluie tombée')),
                ('data_table_status', models.BooleanField(default=True, help_text='Tableau de données')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_active_graph', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_active_graph', to='analytics.zone')),
            ],
        ),
    ]
