# Generated by Django 4.2.16 on 2025-04-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0040_activegraph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='soil_param_1',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='soil_param_2',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='soil_param_3',
        ),
        migrations.AddField(
            model_name='zone',
            name='soil_param_FC',
            field=models.FloatField(default=50, help_text='Field Capacity (FC) in %.'),
        ),
        migrations.AddField(
            model_name='zone',
            name='soil_param_RAW',
            field=models.FloatField(default=50, help_text='Readily Available Water (RAW) in mm.'),
        ),
        migrations.AddField(
            model_name='zone',
            name='soil_param_TAW',
            field=models.FloatField(default=50, help_text='Total Available Water (TAW) in mm.'),
        ),
        migrations.AddField(
            model_name='zone',
            name='soil_param_WP',
            field=models.FloatField(default=50, help_text='Wilting Point (WP) in %.'),
        ),
    ]
