# Generated by Django 4.2.16 on 2025-05-01 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0041_remove_zone_soil_param_1_remove_zone_soil_param_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphname',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone_graph_names', to='analytics.zone'),
        ),
        migrations.AlterField(
            model_name='sensorcolor',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_graph_names', to='analytics.zone'),
        ),
    ]
