# Generated by Django 4.2.16 on 2025-05-14 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0042_alter_graphname_zone_alter_sensorcolor_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecsalinitysensor',
            name='color',
            field=models.CharField(blank=True, default='#dba800', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='ecsoillow',
            name='color',
            field=models.CharField(blank=True, default='#dba800', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='ecsoilmedium',
            name='color',
            field=models.CharField(blank=True, default='#dba800', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='electricityconsumptionsensor',
            name='color',
            field=models.CharField(blank=True, default='#dba800', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='fruitsizesensor',
            name='color',
            field=models.CharField(blank=True, default='#dba800', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='humidityweather',
            name='color',
            field=models.CharField(blank=True, default='#dba800', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='largefruitdiametersensor',
            name='color',
            field=models.CharField(blank=True, default='#dba800', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='leafmoisturesensor',
            name='color',
            field=models.CharField(blank=True, default='#dba800', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='multidepthsoilmoisturesensor',
            name='color',
            field=models.CharField(blank=True, default='#dba800', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='npksensor',
            name='color',
            field=models.CharField(blank=True, default='#dba800', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='phsoil',
            name='color',
            field=models.CharField(blank=True, default='#dba800', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='phwatersensor',
            name='color',
            field=models.CharField(blank=True, default='#dba800', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='precipitationrate',
            name='color',
            field=models.CharField(blank=True, default='#dba800', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='pressureweather',
            name='color',
            field=models.CharField(blank=True, default='#dba800', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='soilechigh',
            name='color',
            field=models.CharField(blank=True, default='#dba800', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='soilmoisturehigh',
            name='color',
            field=models.CharField(blank=True, default='#dba800', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='soilmoisturelow',
            name='color',
            field=models.CharField(blank=True, default='#dba800', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='soilmoisturemedium',
            name='color',
            field=models.CharField(blank=True, default='#dba800', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='soilsalinityconductivityintegratedsensor',
            name='color',
            field=models.CharField(blank=True, default='#dba800', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='soiltemperaturehigh',
            name='color',
            field=models.CharField(blank=True, default='#dba800', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='soiltemperaturelow',
            name='color',
            field=models.CharField(blank=True, default='#dba800', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='soiltemperaturemedium',
            name='color',
            field=models.CharField(blank=True, default='#dba800', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='solarradiation',
            name='color',
            field=models.CharField(blank=True, default='#dba800', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='temperatureweather',
            name='color',
            field=models.CharField(blank=True, default='#dba800', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='waterecsensor',
            name='color',
            field=models.CharField(blank=True, default='#dba800', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='waterflowsensor',
            name='color',
            field=models.CharField(blank=True, default='#dba800', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='waterlevelsensor',
            name='color',
            field=models.CharField(blank=True, default='#dba800', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='winddirection',
            name='color',
            field=models.CharField(blank=True, default='#dba800', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='windspeed',
            name='color',
            field=models.CharField(blank=True, default='#dba800', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='sensorcolor',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_graph_names', to='analytics.zone'),
        ),
    ]
