# Generated by Django 4.2.16 on 2025-05-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0043_ecsalinitysensor_color_ecsoillow_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecsalinitysensor',
            name='courbe_name',
            field=models.CharField(blank=True, default='name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ecsoillow',
            name='courbe_name',
            field=models.CharField(blank=True, default='name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ecsoilmedium',
            name='courbe_name',
            field=models.CharField(blank=True, default='name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='electricityconsumptionsensor',
            name='courbe_name',
            field=models.CharField(blank=True, default='name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fruitsizesensor',
            name='courbe_name',
            field=models.CharField(blank=True, default='Fuite size', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='humidityweather',
            name='courbe_name',
            field=models.CharField(blank=True, default='name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='largefruitdiametersensor',
            name='courbe_name',
            field=models.CharField(blank=True, default='name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leafmoisturesensor',
            name='courbe_name',
            field=models.CharField(blank=True, default='name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='multidepthsoilmoisturesensor',
            name='courbe_name',
            field=models.CharField(blank=True, default='name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='npksensor',
            name='courbe_name',
            field=models.CharField(blank=True, default='name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='phsoil',
            name='courbe_name',
            field=models.CharField(blank=True, default='name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='phwatersensor',
            name='courbe_name',
            field=models.CharField(blank=True, default='name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='precipitationrate',
            name='courbe_name',
            field=models.CharField(blank=True, default='name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pressureweather',
            name='courbe_name',
            field=models.CharField(blank=True, default='name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='soilechigh',
            name='courbe_name',
            field=models.CharField(blank=True, default='name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='soilmoisturehigh',
            name='courbe_name',
            field=models.CharField(blank=True, default='name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='soilmoisturelow',
            name='courbe_name',
            field=models.CharField(blank=True, default='name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='soilmoisturemedium',
            name='courbe_name',
            field=models.CharField(blank=True, default='name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='soilsalinityconductivityintegratedsensor',
            name='courbe_name',
            field=models.CharField(blank=True, default='name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='soiltemperaturehigh',
            name='courbe_name',
            field=models.CharField(blank=True, default='name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='soiltemperaturelow',
            name='courbe_name',
            field=models.CharField(blank=True, default='name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='soiltemperaturemedium',
            name='courbe_name',
            field=models.CharField(blank=True, default='name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='solarradiation',
            name='courbe_name',
            field=models.CharField(blank=True, default='name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='temperatureweather',
            name='courbe_name',
            field=models.CharField(blank=True, default='name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='waterecsensor',
            name='courbe_name',
            field=models.CharField(blank=True, default='name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='waterflowsensor',
            name='courbe_name',
            field=models.CharField(blank=True, default='name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='waterlevelsensor',
            name='courbe_name',
            field=models.CharField(blank=True, default='name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='winddirection',
            name='courbe_name',
            field=models.CharField(blank=True, default='name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='windspeed',
            name='courbe_name',
            field=models.CharField(blank=True, default='name', max_length=50, null=True),
        ),
    ]
