# Generated by Django 4.2.16 on 2025-05-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0044_ecsalinitysensor_courbe_name_ecsoillow_courbe_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='npksensor',
            old_name='color',
            new_name='nitrogen_color',
        ),
        migrations.RemoveField(
            model_name='npksensor',
            name='courbe_name',
        ),
        migrations.RemoveField(
            model_name='npksensor',
            name='value',
        ),
        migrations.AddField(
            model_name='npksensor',
            name='nitrogen_courbe_name',
            field=models.CharField(blank=True, default='N_curve', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='npksensor',
            name='nitrogen_value',
            field=models.FloatField(blank=True, help_text='Nitrogen reading (N).', null=True),
        ),
        migrations.AddField(
            model_name='npksensor',
            name='phosphorus_color',
            field=models.CharField(blank=True, default='#00a86b', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='npksensor',
            name='phosphorus_courbe_name',
            field=models.CharField(blank=True, default='P_curve', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='npksensor',
            name='phosphorus_value',
            field=models.FloatField(blank=True, help_text='Phosphorus reading (P).', null=True),
        ),
        migrations.AddField(
            model_name='npksensor',
            name='potassium_color',
            field=models.CharField(blank=True, default='#4682b4', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='npksensor',
            name='potassium_courbe_name',
            field=models.CharField(blank=True, default='K_curve', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='npksensor',
            name='potassium_value',
            field=models.FloatField(blank=True, help_text='Potassium reading (K).', null=True),
        ),
    ]
