# Generated by Django 4.2.16 on 2025-05-19 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0045_rename_color_npksensor_nitrogen_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilConductivitySensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, help_text='Soil electrical conductivity value.', null=True)),
                ('timestamp', models.DateTimeField()),
                ('color', models.CharField(blank=True, default='#dba800', max_length=7, null=True)),
                ('courbe_name', models.CharField(blank=True, default='Conductivity', max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_conductivity_sensors_per_user', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_conductivity_sensors', to='analytics.zone')),
            ],
        ),
        migrations.CreateModel(
            name='SoilSalinitySensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, help_text='Soil salinity value.', null=True)),
                ('timestamp', models.DateTimeField()),
                ('color', models.CharField(blank=True, default='#1f77b4', max_length=7, null=True)),
                ('courbe_name', models.CharField(blank=True, default='Salinity', max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_salinity_sensors_per_user', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_salinity_sensors', to='analytics.zone')),
            ],
        ),
        migrations.DeleteModel(
            name='SoilSalinityConductivityIntegratedSensor',
        ),
    ]
