# Generated by Django 4.2.16 on 2025-05-21 08:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0047_remove_ecsalinitysensor_color_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SoilECHigh',
            new_name='ECSoilHigh',
        ),
    ]
