# Generated by Django 4.2.16 on 2025-05-23 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0048_rename_soilechigh_ecsoilhigh'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterPressureSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, help_text='Water pressure sensor reading in bar per second.', null=True)),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_pressure_sensors_per_user', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_pressure_sensors', to='analytics.zone')),
            ],
        ),
    ]
