# Generated by Django 4.2.21 on 2025-06-03 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0052_et0calculated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='et0calculated',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='et0_calculated_weather_per_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='et0calculated',
            name='value',
            field=models.FloatField(blank=True, help_text='Evapotranspiration calculated (ET0) in mm/day.', null=True),
        ),
        migrations.AlterField(
            model_name='et0calculated',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='et0_calculated_weather', to='analytics.zone'),
        ),
    ]
