# Generated by Django 4.2.21 on 2025-06-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0053_alter_et0calculated_user_alter_et0calculated_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activegraph',
            name='pluviometrie_status',
        ),
        migrations.AddField(
            model_name='activegraph',
            name='electricity_consumption_status',
            field=models.BooleanField(default=True, help_text='Consommation électrique'),
        ),
        migrations.AddField(
            model_name='activegraph',
            name='fruit_size_status',
            field=models.BooleanField(default=True, help_text='Taille des fruits'),
        ),
        migrations.AddField(
            model_name='activegraph',
            name='large_fruit_diameter_status',
            field=models.BooleanField(default=True, help_text='Diamètre des gros fruits'),
        ),
        migrations.AddField(
            model_name='activegraph',
            name='leaf_sensor_status',
            field=models.BooleanField(default=True, help_text='Capteur de feuille'),
        ),
        migrations.AddField(
            model_name='activegraph',
            name='npk_status',
            field=models.BooleanField(default=True, help_text='Statut NPK'),
        ),
        migrations.AddField(
            model_name='activegraph',
            name='pluviometry_status',
            field=models.BooleanField(default=True, help_text='Cumul de précipitations'),
        ),
        migrations.AddField(
            model_name='activegraph',
            name='water_ec_status',
            field=models.BooleanField(default=True, help_text="Conductivité électrique de l'eau"),
        ),
        migrations.AddField(
            model_name='activegraph',
            name='water_flow_status',
            field=models.BooleanField(default=True, help_text="Débit d'eau"),
        ),
        migrations.AddField(
            model_name='activegraph',
            name='water_ph_status',
            field=models.BooleanField(default=True, help_text="pH de l'eau"),
        ),
        migrations.AddField(
            model_name='activegraph',
            name='water_pressure_status',
            field=models.BooleanField(default=True, help_text="Pression d'eau"),
        ),
        migrations.AlterField(
            model_name='activegraph',
            name='data_table_status',
            field=models.BooleanField(default=True, help_text='Affichage du tableau de données'),
        ),
        migrations.AlterField(
            model_name='activegraph',
            name='et0_status',
            field=models.BooleanField(default=True, help_text="Taux d'évapotranspiration (ET0)"),
        ),
        migrations.AlterField(
            model_name='activegraph',
            name='soil_irrigation_status',
            field=models.BooleanField(default=True, help_text="Statut d'irrigation du sol"),
        ),
    ]
