# Generated by Django 4.2.21 on 2025-06-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0054_remove_activegraph_pluviometrie_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activegraph',
            name='cumulative_precipitation_status',
            field=models.BooleanField(default=True, help_text='Précipitations cumulatives'),
        ),
        migrations.AddField(
            model_name='activegraph',
            name='precipitation_rate_status',
            field=models.BooleanField(default=True, help_text='Taux de précipitations'),
        ),
        migrations.AddField(
            model_name='activegraph',
            name='weather_temperature_humidity_status',
            field=models.BooleanField(default=True, help_text='Température et humidité météo'),
        ),
        migrations.AddField(
            model_name='activegraph',
            name='wind_radar_status',
            field=models.BooleanField(default=True, help_text='Radar du vent'),
        ),
    ]
