# Generated by Django 4.2.16 on 2025-08-28 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0055_activegraph_cumulative_precipitation_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPDWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, help_text='Vapor Pressure Deficit in kPa.', null=True)),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpd_weather_per_user', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpd_weather', to='analytics.zone')),
            ],
        ),
    ]
